= Overview

Produce messages to and consume messages from a Kafka cluster using the Kotlin
version of Java Producer and Consumer, and Kafka Streams API.

= Documentation

You can find the documentation and instructions for running this Kotlin example
at
https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kotlin.html?utm_source=github&utm_medium=demo&utm_campaign=ch.examples_type.community_content.clients-ccloud[https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kotlin.html]

---
Forked version setup guide

This sample project is intend to demonstrate stream producer, consumer, stream app, kafkacat and ksql capability. If you have any setup related question that is not answered here, please use the link above for help.

Once you clone this repo, here are the steps you need to go through the flow:
1. Go to the root folder and call `docker-compose up -d` to start up the suites of docker containers for kafka
2. set java home directory, use java 11

3. Run kafkacat to produce profile result `kafkacat -P -b localhost:9092 -t profile -K$ -T` with payload
```
820a8627-5da3-40c5-b5a7-ec39e5678719${"profileId": "820a8627-5da3-40c5-b5a7-ec39e5678719", "name": "profile1", "ssnDue": false}
```
4. Run transaction producer to create a $70 transaction
